services:
  # Backend service configuration
  - type: web
    name: diabetes-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    
  # Frontend service configuration
  - type: web
    name: diabetes-prediction-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 16
    routes:
      - type: rewrite
        source: /api/*
        destination: https://diabetes-prediction-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html 